import type { Metadata } from "next";
import React from "react";
import './globals.css';
import {cn} from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import {Toaster} from "sonner";

export const metadata: Metadata = {
  title: "Hippo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html className="h-full" lang="en">
          <body className={cn('relative h-full font-sans antialiased')}>
                <Navbar />
                <main className="relative flex flex-col min-h-screen">
                    <Providers>
                         <div className="flex-grow flex-1">{children}</div>
                    </Providers>
                </main>

                <Toaster position="bottom-center" richColors />
          </body>
      </html>
  );
}
